#!/bin/bash

# Relief Net - Firebase Configuration Helper
# Helps you retrieve Firebase credentials quickly

echo "🔥 ReliefNet Firebase Configuration Helper"
echo "==========================================="
echo ""
echo "Project: reliefnet-app"
echo "Project ID: reliefnet-app"
echo ""

echo "📋 STEP 1: Enable Authentication"
echo "================================"
echo "1. Open: https://console.firebase.google.com/project/reliefnet-app/authentication/providers"
echo "2. Click 'Get Started' if needed"
echo "3. Enable 'Email/Password' provider"
echo "4. Click 'Save'"
echo ""
read -p "Press Enter when Authentication is enabled..."

echo ""
echo "📋 STEP 2: Get Web App Credentials (Frontend)"
echo "=============================================="
echo "1. Open: https://console.firebase.google.com/project/reliefnet-app/settings/general"
echo "2. Scroll to 'Your apps' section"
echo "3. Click the Web icon (</>) to add a web app"
echo "4. Name it: ReliefNet Web"
echo "5. Don't enable hosting yet, just click 'Register app'"
echo ""
echo "You'll see a firebaseConfig object. Copy those values."
echo ""
read -p "Press Enter to create the frontend .env file..."

# Create frontend .env
cd "$(dirname "$0")/.."
cp client/.env.example client/.env

echo ""
echo "✅ Created client/.env"
echo "📝 Now edit client/.env and add your Firebase config values:"
echo ""
echo "   nano client/.env"
echo ""
echo "   Replace these values from the Firebase Console:"
echo "   - VITE_FIREBASE_API_KEY"
echo "   - VITE_FIREBASE_MESSAGING_SENDER_ID"
echo "   - VITE_FIREBASE_APP_ID"
echo ""
read -p "Press Enter when you've updated client/.env..."

echo ""
echo "📋 STEP 3: Get Service Account (Backend)"
echo "========================================="
echo "1. Open: https://console.firebase.google.com/project/reliefnet-app/settings/serviceaccounts/adminsdk"
echo "2. Click 'Generate new private key'"
echo "3. Click 'Generate key' in the dialog"
echo "4. A JSON file will be downloaded"
echo ""
read -p "Press Enter when you've downloaded the service account JSON..."

echo ""
echo "Now you need to extract values from the JSON file and add to server/.env"
echo ""
echo "The JSON file contains:"
echo "  - project_id (already set to reliefnet-app)"
echo "  - private_key (copy the entire key including \\n characters)"
echo "  - client_email"
echo ""

# Create backend .env
cp server/.env.example server/.env

echo "✅ Created server/.env"
echo "📝 Now edit server/.env and add the service account values:"
echo ""
echo "   nano server/.env"
echo ""
echo "   Update these from the downloaded JSON:"
echo "   - FIREBASE_PRIVATE_KEY (must include the newlines as \\n)"
echo "   - FIREBASE_CLIENT_EMAIL"
echo ""
read -p "Press Enter when you've updated server/.env..."

echo ""
echo "🎉 Configuration Complete!"
echo "=========================="
echo ""
echo "Now you can start the application:"
echo ""
echo "  Terminal 1 (Backend):"
echo "    cd server && pnpm dev"
echo ""
echo "  Terminal 2 (Frontend):"
echo "    cd client && pnpm dev"
echo ""
echo "  Then visit: http://localhost:5173"
echo ""
echo "📖 For more details, see FIREBASE_SETUP.md"
